repos:
-   repo: https://github.com/ambv/black
    rev: cb67a322423cb2b4bcfb2faa68fb769326741d6a
    hooks:
    - id: black
      args: []
      python_version: python3.8
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: flake8
-   repo: git://github.com/timothycrosley/isort 
    rev: master
    hooks:
    - id: isort
