repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: git://github.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
-   repo: git://github.com/timothycrosley/isort 
    rev: master
    hooks:
    - id: isort
